site_name: zappend

nav:
  - Introduction: intro.md
  - Getting Started: start.md
  - User Guide: guide.md
  - CLI Reference: cli.md
  - API Reference: api.md
  - Configuration: config.md
  - About: about.md

theme: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_root_heading: false
            show_source: false
            heading_level: 3
            annotations_path: brief

